services:
  spring-boot-app:
    container_name: spring-boot-app
    build: .
    image: spring-boot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://spring-boot-mysql:3306/sbmd?createDatabaseIfNotExist=true
    ports:
      - 9090:8080
  ## MySQL Docker Compose Config
  spring-boot-mysql:
    container_name: spring-boot-mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'sbmd'
      #MYSQL_USER: 'sbmd'
      #MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - ./mysql_os_data:/var/lib/mysql
    restart: unless-stopped